stages: 
  - build
  - deploy 
  - compile

cache:
  untracked: true
  paths:
  - node-modules/
  - out/

prepare:
  stage: build
  script: 
    - pm2 kill
    - npm install
  tags:
    - gabko

start:
  stage: deploy
  script:
    - pm2 kill
    - pm2 start ecosystem.config.js --env production
  tags:
    - gabko