export { createUser } from "./users/create-user";
export { login } from "./users/login";
export { resetPassword } from "./users/reset-pass";
export { newPassword } from "./users/new-password"
export { getFinca } from "./fincas/get-finca";
export { addFinca } from "./fincas/add-finca";
export { deleteFinca } from './fincas/delete-finca'
export { updateFinca } from './fincas/update-finca'
export { getBovinos } from "./bovinos/get-bovinos";
export { addBovino } from "./bovinos/add-bovino";
export { updateBovino } from "./bovinos/update-bovino";
export { deleteBovino } from "./bovinos/delete-bovino";
export { addImageBovino } from "./bovinos/add-image-bovino";
export { getImageBovino } from "./bovinos/get-image-bovino";