export { insert } from "./users/insert";
export { login } from "./users/login";
export { resetPassword } from "./users/reset-pass";
export { newPassword } from "./users/new-password"
export { getBovinos } from "./bovinos/get-bovinos";
export { addBovino } from "./bovinos/add-bovino";
export { getBovino } from "./bovinos/get-bovino";
export { updateBovino } from "./bovinos/update-bovino";
export { deleteBovino } from "./bovinos/delete-bovino";
export * from "./alimentacion/get-alimentacion";
export { addAlimentacion } from "./alimentacion/add-alimentacion";
export { deleteAlimentacion } from "./alimentacion/delete-alimentacion";
export { updateAlimentacion } from "./alimentacion/update-alimentacion";
export { getCeba } from "./ceba/get-ceba";
export { addCeba } from "./ceba/add-ceba";
export { updateCeba } from "./ceba/update-ceba";
export { deleteCeba } from "./ceba/delete-ceba";
export { getFinca } from "./finca/get-finca";
export { updateFinca } from "./finca/update-finca";
export { deleteFinca } from "./finca/delete-finca";
export { addFinca } from "./finca/add-finca";
export { getLecheByIdFinca } from "./leche/get-leche-by-id-finca";
export { addLeche } from "./leche/add-leche";
export { updateLeche } from "./leche/update-leche";
export { deleteLeche } from "./leche/delete-leche";
export * from "./manejo/get-manejo";
export { addManejo } from "./manejo/add-manejo";
export { updateManejo } from "./manejo/update-manejo";
export { deleteManejo } from "./manejo/delete-manejo";
export { getPajillasyIdFinca } from "./pajilla/get-pajilla";
export { addPajilla } from "./pajilla/add-pajilla";
export { deletePajilla } from "./pajilla/delete-pajilla";
export { updatePajilla } from "./pajilla/update-pajilla";
export { getProduccion } from "./produccion/get-produccion";
export { addProduccion } from "./produccion/add-produccion";
export { deleteProduccion } from "./produccion/delete-produccion";
export { updateProduccion } from "./produccion/update-produccion";
export * from "./sanidad/get-sanidad";
export { addSanidad } from "./sanidad/add-sanidad";
export { updateSanidad } from "./sanidad/update-sanidad";
export { deleteSanidad } from "./sanidad/delete-sanidad";
export * from "./vacuna/get-vacuna";
export { updateVacuna } from "./vacuna/update-vacuna";
export { addVacuna } from "./vacuna/add-vacuna";
export { deleteVacuna } from "./vacuna/delete-vacuna";


